version: '3'

services:
  nerv-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nerv-celestial-tracker
    # Removed ports mapping to prevent exposing to host
    restart: unless-stopped
    # Uncomment the volumes section during development for live updates
    # volumes:
    #   - ./:/usr/share/nginx/html 